_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
DATASETS:
  TRAIN: ('t3_voc_coco_2007_val_with_known_and_unk', )
  TEST: ('voc_coco_2007_test', )
SOLVER:
  STEPS: (110000, 112000)
  MAX_ITER: 50000
  WARMUP_ITERS: 0
OUTPUT_DIR: "./output/t3_train_with_unk"
OWOD:
  ENABLE_CLUSTERING: False
  ENABLE_THRESHOLD_AUTOLABEL_UNK: False
  PREV_INTRODUCED_CLS: 40
  CUR_INTRODUCED_CLS: 20
  CLUSTERING:
    START_ITER: 74000