_BASE_: "../../../Base-RCNN-C4-OWOD.yaml"
MODEL:
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "/home/fk1/workspace/OWOD/output/iOD/19_p_1_ft/model_final.pth"
  ROI_HEADS:
    #    NUM_CLASSES: 21 # 0-19 Known class; 20 -> Unknown; 21 -> Background.
    NUM_CLASSES: 21
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
DATASETS:
  TRAIN: ('voc_2007_trn_ft', )
  TEST: ('voc_2007_test', )
SOLVER:
  STEPS: (32000,34000)
  MAX_ITER: 36000
  WARMUP_ITERS: 100
OUTPUT_DIR: "./output/iOD/19_p_1_ft"
OWOD:
  ENABLE_THRESHOLD_AUTOLABEL_UNK: False
  ENABLE_CLUSTERING: False
  PREV_INTRODUCED_CLS: 19
  CUR_INTRODUCED_CLS: 1
SEED: 9999